In [17]:
import numpy as np
t = np.array([
                [
                    [
                        [1],
                        [2]
                    ],
                    [
                        [3],
                        [4]
                    ],
                    [
                        [5],
                        [6]
                    ]
                ],
                [
                    [
                        [7],
                        [8]
                    ],
                    [
                        [9],
                        [10]
                    ],
                    [
                        [11],
                        [12]
                    ]
                ],
                [
                    [
                        [13],
                        [14]
                    ],
                    [
                        [15],
                        [16]
                    ],
                    [
                        [17],
                        [18]
                    ]
                ]
            ])

In [37]:
tensor_4.T

array([[[[ 1,  7, 13],
         [ 3,  9, 15],
         [ 5, 11, 17]],

        [[ 2,  8, 14],
         [ 4, 10, 16],
         [ 6, 12, 18]]]])

In [38]:
tensor_4.T.shape

(1, 2, 3, 3)

In [22]:
# len(tensor) = number of elements in outer dimension
# num of [ in tensor == number of dimensions
# shape return a tuple => len(shape) == number of dimensions
# each number in shape tuple == number of elements for each dimension  
len(tensor_4), tensor_4.shape, len(tensor_4.shape)

(3, (3, 3, 2, 1), 4)

In [23]:
tensor_2 = np.array([[3, 2]])
len(tensor_2), tensor_2.shape, len(tensor_2.shape)

(1, (1, 2), 2)

In [28]:
tensor_1 = np.array([3, 2])
len(tensor_1), tensor_1.shape, len(tensor_1.shape)

(2, (2,), 1)

In [30]:
tensor_0 = np.array(5)
tensor_0.shape, len(tensor_0.shape)

((), 0)

In [31]:
inputs = np.array([[-0.27,  0.45,  0.64, 0.31]])
weights = np.array([[0.02, 0.001, -0.03, 0.036], [0.04, -0.003, 0.025, 0.009], [0.012, -0.045, 0.28, -0.067]])
inputs.shape, weights.shape

((1, 4), (3, 4))

In [34]:
np.matmul(inputs, weights.T)

array([[-0.01299,  0.00664,  0.13494]])

In [39]:
np.matmul(weights, inputs.T)

array([[-0.01299],
       [ 0.00664],
       [ 0.13494]])

In [53]:
# Use the numpy library
import numpy as np


def prepare_inputs(inputs):
    # TODO: create a 2-dimensional ndarray from the given 1-dimensional list;
    #       assign it to input_array
    input_array = np.array([inputs])
    
    # TODO: find the minimum value in input_array and subtract that
    #       value from all the elements of input_array. Store the
    #       result in inputs_minus_min
    mini = np.min(inputs)
    inputs_minus_min = input_array - mini

    # TODO: find the maximum value in inputs_minus_min and divide
    #       all of the values in inputs_minus_min by the maximum value.
    #       Store the results in inputs_div_max.
    maxi = np.max(inputs_minus_min)
    inputs_div_max = inputs_minus_min / maxi

    # return the three arrays we've created
    return input_array, inputs_minus_min, inputs_div_max
    

def multiply_inputs(m1, m2):
    # TODO: Check the shapes of the matrices m1 and m2. 
    #       m1 and m2 will be ndarray objects.
    #
    #       Return False if the shapes cannot be used for matrix
    #       multiplication. You may not use a transpose
    if m1.shape[1]!=m2.shape[0] and m2.shape[1]!=m1.shape[0]:
        return False

    # TODO: If you have not returned False, then calculate the matrix product
    #       of m1 and m2 and return it. Do not use a transpose,
    #       but you swap their order if necessary
    if m1.shape[1]==m2.shape[0]:
        return np.matmul(m1,m2)
    else:
        return np.matmul(m2,m1)
    

def find_mean(values):
    # TODO: Return the average of the values in the given Python list
    return np.mean(values)


input_array, inputs_minus_min, inputs_div_max = prepare_inputs([-1,2,7])
print("Input as Array: {}".format(input_array))
print("Input minus min: {}".format(inputs_minus_min))
print("Input  Array: {}".format(inputs_div_max))

print("Multiply 1:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3],[4]]))))
print("Multiply 2:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3]]))))
print("Multiply 3:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1,2]]))))

print("Mean == {}".format(find_mean([1,3,4])))

Input as Array: [[-1  2  7]]
Input minus min: [[0 3 8]]
Input  Array: [[ 0.     0.375  1.   ]]
Multiply 1:
False
Multiply 2:
[[14]
 [32]]
Multiply 3:
[[ 9 12 15]]
Mean == 2.6666666666666665


In [47]:
np.array([[1,2,3],[4,5,6]]).shape[0]

2