In [31]:
%%timeit
from numpy import exp, array, random, dot

class NeuralNetwork:
    def __init__(self):
        random.seed(1)
        self.synaptic_weights = 2 * random.random((3,1)) - 1  # shape (3,1)
        self.learnrate = 2.2
    
    def __sigmoid(self, x):
        return 1 / (1 + exp(-x))
    
    def __sigmoid_derivative(self, x):
        return self.__sigmoid(x) * (1 - self.__sigmoid(x))
    
    def predict(self, inputs):
        return self.__sigmoid(dot(inputs, self.synaptic_weights))
    
    def train(self, training_set_inputs, training_set_outputs, number_of_epochs):
        for epoch in range(number_of_epochs):
            output = self.predict(training_set_inputs) # shape (4,1)
            error = training_set_outputs - output
            error_term = error * self.__sigmoid_derivative(output)
            adjustment = dot(training_set_inputs.T, self.learnrate * error_term) # shape (3, 4)*(4,1) => (3,1)
            self.synaptic_weights += adjustment
        
        
if __name__ == '__main__':
    
    neural_network = NeuralNetwork()
    print('Random setup weights:')
    print(neural_network.synaptic_weights)
    
    training_set_inputs = array([[0,0,1],[1,1,1],[1,0,1],[0,1,1]]) # shape (4,3)
    training_set_outputs = array([[0,1,1,0]]).T # shape (4,1)
    
    neural_network.train(training_set_inputs, training_set_outputs, 25000)
    
    print('Weigths after training:')
    print(neural_network.synaptic_weights)
    
    print('Predict:')
    validate_input = array([1,0,0])
    print(neural_network.predict(validate_input))

Random setup weights:
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
Weigths after training:
[[ 18.45177718]
 [ -0.40562103]
 [ -8.94041314]]
Predict:
[ 0.99999999]
Random setup weights:
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
Weigths after training:
[[ 18.45177718]
 [ -0.40562103]
 [ -8.94041314]]
Predict:
[ 0.99999999]
Random setup weights:
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
Weigths after training:
[[ 18.45177718]
 [ -0.40562103]
 [ -8.94041314]]
Predict:
[ 0.99999999]
Random setup weights:
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
Weigths after training:
[[ 18.45177718]
 [ -0.40562103]
 [ -8.94041314]]
Predict:
[ 0.99999999]
Random setup weights:
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
Weigths after training:
[[ 18.45177718]
 [ -0.40562103]
 [ -8.94041314]]
Predict:
[ 0.99999999]
Random setup weights:
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
Weigths after training:
[[ 18.45177718]
 [ -0.40562103]
 [ -8.94041314]]
Predict:
[ 0.99999999]
Random setup wei